name: test
on: [push]
jobs:
  test:
    name: Build and test
    strategy:
      matrix:
        os:
          # intel
          - macos-13
          - ubuntu-latest
          # arm64
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig build run
