name: test
on: [push]

jobs:
  build:
    name: Build release targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - name: Build
        run: zig build release --summary all
      - name: Inspect binaries
        run: ls -lh zig-out/*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-targets
          path: zig-out/
  test:
    name: Download and run
    needs: [build]
    strategy:
      matrix:
        include:
          # TODO: Arm64 ubuntu runner is not supported in private repo yet.
          # TODO: Run gnu & musl in one job.
          - os: macos-latest
            target: aarch64-macos
          - os: ubuntu-latest
            target: x86_64-linux-gnu
          - os: ubuntu-latest
            target: x86_64-linux-musl
          - os: macos-13
            target: x86_64-macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-targets
          path: zig-out/
      - name: Run binary
        run: |
          chmod +x "${EXE}"
          "${EXE}"
        env:
          EXE: ./zig-out/${{ matrix.target }}/cpu-mem-stat
